### ISSUE TITLE
Не работает включение двухфакторной аутентификации

### ISSUE THREAD

**Issue by VitalD** [anilibria/anilibria#106]
При вводе кода появляется сообщение "Неправильный код 2FA".

**Comment by Asethon** [comment]
Двухфакторка привязана к Гуглу. Локальный скрипт до него не достучится и не сможет сгенерить код, что ожидаемо.
При локальной разработке проще это обрубать.

**Comment by VitalD** [comment]
Я увы не силен в вопросах внутренней реализации, поэтому не понимаю, что за привязку к Гугл вы имеете в виду. Мне казалось тут всё устроено так, что сайт генерирует ключ, этот ключ заносится в приложение пользователя (не обязательно от Гугла), приложение по ключу постоянно генерирует коды для входа. Проблема возникает именно при попытке подтвердить включение кодом полученным из приложения. Про какую локальную разработку вы говорите?

**Comment by Kirjaa** [comment]
У нас есть проблема с кэшированием, из-за чего полученные ключи обновляются не сразу.
Когда вы получаете ключ, нужно его ввести и раз в пару секунд нажимать кнопку, в какой-то момент кэш обновится и пропустит код.
