### ISSUE TITLE
Громкость плеера не сохраняется.

### ISSUE THREAD

**Issue by 1ike** [anilibria/anilibria#112]
По крайней мере, на Firefox. Да еще и зависло на значении близком к максимуму. Началось где-то не больше месяца назад. Посмотрел на дату последнего комита [player.js](https://github.com/anilibria/anilibria/blob/c612556b5c3b8968c6ba38b9a2fb6b82832a7e08/js/player.js) - 4 месяца назад. Странно. Своими силами решить не могу, с помощью userscript устанавливаю начальную громкость плеера (0.3), но при этом отображается зависшее значение и если потом решить поменять громкость прокруткой колесиком мыши идет резкий скачок к зависшему значению и регулировка начинается от него.

**Comment by Kirjaa** [comment]
у меня с громкостью на Firefox проблем нет, как выставляю - так и запоминает. Попробуйте поискать проблему у себя в браузере, возможно какие-то плагины мешают нормальной работе плеера.

**Comment by 1ike** [comment]
Да, сейчас проверил на других операционках - сохраняет громкость. А на моем текущем firefox - не сохраняет, что с вручную отключенными дополнениями, что при запуске в безопасном режиме. В общем, частный случай. Извиняюсь, что более тщательно не потестил проблему,  надо закрыть issue.
