### ISSUE TITLE
Некорректно работает пагинация в списке релизов.

### ISSUE THREAD

**Issue by Ozulon** [anilibria/anilibria#114]
Браузер Microsoft Edge Версия 93.0.961.52
В списке релизов, если перейти на какую-то из страниц, а после обновить страницу в браузере, список релизов переходит на первую страницу.
Аналогично, если пройти по ссылке на какую-то из страниц релизов, то мы попадаем на первую страницу, а не на ту, что указана в ссылке: https://www.anilibria.tv/pages/catalog.php#page-3

**Comment by Kirjaa** [comment]
Проблема известна, исправим уже с новым фронт-эндом скорее всего.
