### ISSUE TITLE
Cloudflare защита домена static.*

### ISSUE THREAD

**Issue by AgentMC** [anilibria/anilibria#116]
Привет, сегодня не смог загрузить торренты в qBitTorrent, похоже по домену static.anilibria.tv работает cloudflare 
Например
https://static.anilibria.tv/upload/torrents/17417.torrent
![image](https://user-images.githubusercontent.com/11662240/139487186-47570ba5-bffa-4d40-84cf-5b895994b1db.png)
Через браузер, понятно, всё грузится, но массовая подгрузка торрентов по ссылкам из qBitTorrent теперь не работает
![image](https://user-images.githubusercontent.com/11662240/139487393-fd7dace2-358f-4c7f-9fd6-babdfb4a70f0.png)
Подкидывать куки через qBT пробовал, не работает. 

Что посоветуете для авто-скачки торрентов?

**Comment by Kirjaa** [comment]
Добрый день! Защита уже отключена с максимальной на пониженную. Это временные меры, так что если сайт подвергается ддос атаке, то приходится немного потерпеть.

**Comment by AgentMC** [comment]
Ясно, буду знать, спасибо.
