### ISSUE TITLE
В расписание добавить пункт "по мере готовности"

### ISSUE THREAD

**Issue by OmlineEditor** [anilibria/anilibria#118]
Вы делаете аниме в основном по рассписанию и на сайте есть дни с понедельника по воскресенье. Я прошу вас добавить на страницу с расписанием еще вариант "по мере готовности" и в этом списке будут аниме которые сейчас в работе и которые выходят по мере готовности без четкого рассписания. Так понятнее будет и люди не будут вас ругать что серия задерживается.

**Comment by ApostolDmitry** [comment]
> Вы делаете аниме в основном по рассписанию и на сайте есть дни с понедельника по воскресенье. Я прошу вас добавить на страницу с расписанием еще вариант "по мере готовности" и в этом списке будут аниме которые сейчас в работе и которые выходят по мере готовности без четкого рассписания. Так понятнее будет и люди не будут вас ругать что серия задерживается.

В это просто не смысла. На данный момент на сайте уже есть функция анонса, которая позволяет уведомить пользователей, что серия задерживается.

**Comment by OmlineEditor** [comment]
Это вы говорите про текст на основной постере?
