### ISSUE TITLE
Некорректно отображается шапка и меню сайта

### ISSUE THREAD

**Issue by mikhailkurakhtanov** [anilibria/anilibria#128]
Рекомендую чутка уменьшить или заменить семейство шрифтов, а также прикрепить меню кверху, сместив шапку с логотипом Анилибрии на нужное место перед рекламой Патреона)
![image](https://user-images.githubusercontent.com/53254251/152667876-c9ab74ed-c862-4ff9-946f-164581e9b7a1.png)

**Comment by Kirjaa** [comment]
С шрифтами была проблема - исправили.
А вот по поводу логотипа - отключите адблок и появится нормальная шапка которую он срезает. Если вам не нравится реклама на сайте, то её можно отключить в личном кабинете абсолютно бесплатно, с регистрацией без смс.
