### ISSUE TITLE
Anilibria API не возвращает больше Постеры релизов 

### ISSUE THREAD

**Issue by AgentMC** [anilibria/anilibria#138]
Возможно, связано с https://github.com/anilibria/anilibria/commit/fbd7d74a71d5e1bea066fa6aef76da4c6755e8eb

Начиная с 27-05-2022, около 22:30 UTC, api.anilibria.tv возврашает свойство Posters вот так для всех релизов:
```
    "posters": {
      "small": { "raw_base64_file": null },
      "medium": { "raw_base64_file": null },
      "original": { "raw_base64_file": null }
    },
```
Отсутствует свойство Url.

**Comment by AgentMC** [comment]
П.С. классический апи (index.php) работает нормально.

**Comment by pavloniym** [comment]
Исправили, спасибо!
