### ISSUE TITLE
Кодовая база нуждается в серьёзной переработке

### ISSUE THREAD

**Issue by unti1x** [anilibria/anilibria#143]
Не хочу сказать ничего плохого, но в последний раз подобный подход к архитектуре на php был актуален в начале-середине нулевых. Но с тех пор очень многое изменилось и сейчас php - это не просто шаблонизатор с дополнительными возможностями. Основные проблемы в текущей реализации следущие:

- отсутствие единой точки входа (front controller). больше точек входа = больше возможностей для поломки, а так же растущая сложность кода
- запутанность. в запутанный код легче проникают неочевидные ошибки
- высокая связанность отдельных компонентов. чем выше связанность, тем сложнее тестировать код
- большое количество шаблонного кода. больше шаблонного кода = сложнее поддержка из-за повышенной сложности и сложнее разработка нового функционала
- используется pdo в чистом виде без orm, репозитория и миграций. нет orm - больше шаблонного кода, нет репозитория - весь функционал свален в `func.php`, нет миграций - при любых изменениях схемы базы нужно править её на проде руками, повышается опасность человеческих ошибок и ухудшается приём изменений, когда работает несколько человек
- полное отсутствие тестов, не считая крайне сомнительных функциональных тестов апи. никто не может гарантировать, что исправление кода в одном месте ничего не сломает в другом, нужно каждый раз проверять руками
- наличие кода сайта в открытом доступе. нужно быть весьма уверенным в качестве и безопасности кода, чтобы выставлять его на показ. лично я за пару часов смог найти несколько скользких мест, которые, к счастью, нельзя проэксплуатировать очевидными методами, но это совсем не значит, что нет тех, которые можно: я просто недостаточно хорошо хотел их найти

И этот список можно продолжать дальше. Что делать? Специально для этого и есть фреймворки, например, Symfony, Laravel, Yii, Laminas и ещё куча других. Ещё есть паттерны проектирования, которые придумали не просто, чтобы говорить модные слова: они нужны прежде всего для того, чтобы код было проще делить на независимые части и тестировать.

**Comment by Kirjaa** [comment]
Добрый день!
Спасибо за замечания, я пытался при разработке текущего сайта, убедить прошлого тех. админа, что надо бы использовать фреймворк а не писать велосипеды с древним кодом, но его это не убедило.
Но не беспокойтесь, данный репозиторий у нас считается как legacy, и более не разрабатывается. Исправляем только что-то критическое или обновления базы.
Мы запустили новый бекэнд на ларавеле в январе этого года, фронт к сожалению все ещё не готов, по этому пока пользуемся старым сайтом как фронтом.
