### ISSUE TITLE
Преколы от разработчиков.

### ISSUE THREAD

**Issue by Half-dev** [anilibria/anilibria#150]
![IMG_20221129_234028](https://user-images.githubusercontent.com/77497904/204654069-65cfe5af-6de1-41df-8cad-faceb5a72124.jpg)
Как я понял, это не баг а фича.

**Comment by T1MOXA** [comment]
Вполне возможно что это фича браузера запрещающая использование сторонних куки.

**Comment by strelokhalfer** [comment]
Или что то выпиливает социальные сети (адблокеры например)

**Comment by OmlineEditor** [comment]
То что вы выделили там должны быть комменты из ВКонтакте, но их кто-то вырезал, наверное блокировщик рекламы. Это не глюк разрабов.
