### ISSUE TITLE
Проблемы / предложения

### ISSUE THREAD

**Issue by levcoder** [anilibria/anilibria#158]
1. Обновите структуру проекта в файле [sql](https://github.com/anilibria/anilibria/tree/main/sql)/main.sql поскольку файлов миграции я нигде не нашел, а в проекте уже были добавленные новые таблицы в БД. ( критично не хватает для работы с проектом )
2. По возможности попробовать рассмотреть вариант переноса проекта на какой то популярный фреймворк ( как вариант laravel ), поскольку в текущий кастом намного сложнее что то добавлять.
3. и т.д. но все зависит от этих пунктов, особенно первого

**Comment by pavloniym** [comment]
Добрый вечер.
Мы сейчас не развиваем этот репозиторий. Сейчас он считается уже legacy, который мы только поддерживаем и правим критичные баги.

Основной бекенд уже давно работает и развивается на Laravel. Там есть все миграции, docker, админка и прочие вещи для управления контентом + в разработке внешний API, к которой будет подключен новый фронт (тоже в разработке, vue3 + nuxt3). Эти репозитории закрыты, т.к. находятся в активной разработке. Будут ли они открыты для публичного изучения — не могу сказать...

Поэтому, текущий репозиторий — просто устаревший фронт, без какой-то особой логики, который подключен к новой БД, чтобы пользователи могли пользоваться сайтом (+ обратная совместимость для всех потребителей API v1).
