### ISSUE TITLE
"Сообщить об ошибке" не работает (возможно)

### ISSUE THREAD

**Issue by DespairScent** [anilibria/anilibria#161]
При отправке сообщения об ошибке кнопка отправки просто пропадает. Нет никакого отклика о том, что сообщение было успешно отправлено. Запрос к /public/error.php выдает ошибку 500.

**Comment by DespairScent** [comment]
Не нашел куда можно сообщать о недочетах актуального сайта. Можно ли сюда в случае чего, или стоит куда то в другое место?

**Comment by pavloniym** [comment]
@DespairScent 
Добрый вечер, можете писать сюда, по возможности реагируем.
P.S. [маленькая ремарка](https://github.com/anilibria/anilibria/issues/158#issuecomment-1456717404)

**Comment by DespairScent** [comment]
Было исправлено?
