### ISSUE TITLE
Мы комадна Modern Design Team хотим сделает редизайн сайта анилибрии как можно с вами связаться?

### ISSUE THREAD

**Issue by Half-designer** [anilibria/anilibria#163]
Тайтл

**Comment by pavloniym** [comment]
Добрый день!
У нас сейчас есть макет нового дизайна, который находится на этапе верстки и реализации.
Можно ли посмотреть ваше портфолио и интересно ли вам вписаться в доработку такого макета?

**Comment by Half-designer** [comment]
> Добрый день! У нас сейчас есть макет нового дизайна, который находится на этапе верстки и реализации. Можно ли посмотреть ваше портфолио и интересно ли вам вписаться в доработку такого макета?

Надо спрашивать у участников, команда появилась резко и неожиданно только чтобы поменять дизайн анилбрии, из портфолио, я могу и участники могут предоставить пару проектов, а и кстати как можно с вами связаться.
(Вся команда была построена чтобы помочь анилибрии из добровольцев за бесплатно)

**Comment by pavloniym** [comment]
Телеграм @Kirjaa у вас есть, пишите туда
