### ISSUE TITLE
Добавление в избранные не работает в APIv3

### ISSUE THREAD

**Issue by eugene-sukhodolskiy** [anilibria/anilibria#168]
Примерно с 12 апреля, попытка добавления тайтла в избранные посредством запроса APIv3 возвращает ошибку 500.

**Comment by eugene-sukhodolskiy** [comment]
Заметил, что когда добавляешь новый тайтл, ответ 200, но в избранных добавленный тайтл не появляется и после последующие попытки возвращают ошибку 500

**Comment by T1MOXA** [comment]
Удалось воспроизвести проблему, но только при повторном добавлении в избранное, когда тайтл уже был в избранном.
Исправим этот момент.
Спасибо что обратили внимание на проблему!
