### ISSUE TITLE
Пагинация в APIv3 не работает

### ISSUE THREAD

**Issue by eugene-sukhodolskiy** [anilibria/anilibria#169]
Уже очень давно не работает пагинация в APIv3. Для проверки предлагаю следующую инструкцию:

- Выполним поисковый запрос c текстом **nan** с выводом 10 результатов на страницу, чтоб убедиться, что по запросу **nan** существует минимум 10 тайтлов. https://api.anilibria.tv/api/v3/title/search?page=1&items_per_page=10&filter=id&search=nan
- Выполним тот же запрос, но попросим только 5 результатов со второй страницы https://api.anilibria.tv/api/v3/title/search?page=2&items_per_page=5&filter=id&search=nan в ответ возвращается 0 результатов.

**Comment by T1MOXA** [comment]
Спасибо за баг репорт.
Будет исправлено в будущем обновлении!
