### ISSUE TITLE
добавить опций скачивания

### ISSUE THREAD

**Issue by lexillar** [anilibria/anilibria#170]
хотелось бы например веб-пожатое 720р скачивать
или торрентом, или дать возможность yt-dlp качать из веба

**Comment by pavloniym** [comment]
Вы можете скачивать HEVC раздачи, они есть в 99% случаев — это лучшее соотношение размер/разрешение. Других способов скачивания не планируется, т.к. это дополнительные ресурсы и мощности, на которые команда проекта решила пока не тратить свои силы

**Comment by lexillar** [comment]
понятно, спасибо.
HEVC не всё железо поддерживает.
а что насчёт веб скачивания? я пробовал yt-dlp и склеивать .m3u8 с помощью vlc . и оба способа почему-то не работают. Может у плеера есть какие-то защиты контента, которые можно без особых затрат труда отключить?
