### ISSUE TITLE
Текст описания выходит за пределы карточки аниме

### ISSUE THREAD

**Issue by Damego** [anilibria/anilibria#173]
Данное аниме имеет очень длинное название и из-за чего микро описание не влезает в контейнер

![image](https://user-images.githubusercontent.com/25762802/232722947-6bf6124b-5f09-4c74-8193-0fa2a765dcab.png)

**Comment by Kirjaa** [comment]
Исправлено в коммите https://github.com/anilibria/anilibria/commit/d14b88873ea2ce223adbca0fe80f9fd7e329f506
Теперь если название слишком длинное - описания не будет.
