### ISSUE TITLE
Смещение перемотки в firefox

### ISSUE THREAD

**Issue by TristisOris** [anilibria/anilibria#174]
в фулскрине идет сдвиг от места наведения на таймлайн до фактического тайминга. Чем дальше от начала, тем больше сдвиг.
уже с пол года наверно.

![ani_fs](https://user-images.githubusercontent.com/1270117/232856376-c54bf0d2-2b97-417b-a21c-976cc83a8b02.gif)

**Comment by Kirjaa** [comment]
мы обновили плеер, проблема ещё актуальна?
