### ISSUE TITLE
Api субдомен мертв?

### ISSUE THREAD

**Issue by AgentMC** [anilibria/anilibria#175]
`https://api.anilibria.tv/v2.13.1/getChanges?limit=50` --> 502
`https://api.anilibria.tv/v3.0.14/feed` --> 502

**Comment by pavloniym** [comment]
Добрый вечер.
Были тех.проблемы с серверами
Сейчас все должно работать стабильно.
P.S. `https://api.anilibria.tv/v3.0.14/feed` -> 500 — о проблеме сообщили, работаем над устранением, спасибо!
