### ISSUE TITLE
Сломалось запоминание тайминга для серий.

### ISSUE THREAD

**Issue by kopoba** [anilibria/anilibria#176]
При появлении новой серии и переходе на страницу аниме мне отображается предпоследняя серия с паузой на тайминге где я закончил просмотр.
Я как обычно жму на переход к следующей(skip forward) серии вот этой серенькой кнопкой
![image](https://github.com/anilibria/anilibria/assets/5034345/ba975e34-2a08-4718-97cd-2605af8cf184)
и попадаю на следующую серию.
Но проблема в том что следующая серия стартует с того же тайминга на котором я закончил просмотр предыдущей серии. 
Нажатие на переход к предыдущей серии и а затем к следующей серии вообще затирает история таймингов для них.
Сломалось неделю или две назад.
При этом при переходе на следующую серию из выпадающего списка серия стартует ка положено с начала.
Windows 10, Firefox

**Comment by Kirjaa** [comment]
Исправлено в коммите #9c74084
