### ISSUE TITLE
Виджет комментариев VK сломан под Firefox

### ISSUE THREAD

**Issue by Qurcaivel** [anilibria/anilibria#177]
Проверено:
- Linux;
- Android.

Версия браузера: 115.0.2.

![preview](https://github.com/anilibria/anilibria/assets/52575966/a3c211fc-e02b-4c13-a6ee-fee3c3453fa7)

**Comment by Qurcaivel** [comment]
Проверено:
- Windows.

![preview](https://github.com/anilibria/anilibria/assets/52575966/b53f521e-454d-4bfd-b5e6-c103d55514fa)

**Comment by CAT-i0n** [comment]
Тоже самое

**Comment by Qurcaivel** [comment]
Похоже, проблема была исправлена разработчиками виджета.
