### ISSUE TITLE
Ошибка при попытке отправить письмо для восстановления пароля

### ISSUE THREAD

**Issue by vedorofeev** [anilibria/anilibria#182]
Шаги воспроизведения:
1. Перейти на страницу "Забыли пароль", https://anilibria.life/index.php?do=lostpassword
2. Ввести адрес почты в форму, нажать кнопку "Восстановить"
3. Ознакомиться с полученной информацией на странице: "Could not instantiate mail function."

Изначально попал на страницу из-за того, что не сработал вход через Вконтакте, хотя ранее аккаунт Вконтакте был привязан к учетной записи

**Comment by pavloniym** [comment]
Здравствуйте. 
анилибрия.лайф не является сайтом АниЛибрии, это копия, мы к нему ни имеем никакого отношения.
