### ISSUE TITLE
Не работает вывод информации "Топ 20 прямо сейчас"

### ISSUE THREAD

**Issue by owner** [anilibria/anilibria#26]
![2019-02-14-00 09 17](https://user-images.githubusercontent.com/24358937/52744288-561ce680-2fed-11e9-86ad-a5b6ed844fea.png)

![2019-02-14-00 14 09](https://user-images.githubusercontent.com/24358937/52744330-7ba9f000-2fed-11e9-8080-b1c98b29b78b.png)
Ссылка, где отсутствует вывод: https://www.anilibria.tv/release/mob-psycho-100-2.html
Ссылка на тайтл, где он есть: https://www.anilibria.tv/release/mahou-shoujo-tokushusen-asuka.html

**Comment by poiuty** [comment]
Поправил.
