### ISSUE TITLE
Ошибка стилей

### ISSUE THREAD

**Issue by dmitriitux** [anilibria/anilibria#31]
Стили грузятся внутри <body> - что не принято, а так же тяжело переопределять. Все стили по идее должны быть в блоке <head>, либо в файлах, либо в <style>.
https://stackoverflow.com/questions/1303416/does-style-have-to-be-in-the-head-of-an-html-document

**Comment by Kirjaa** [comment]
можете пожалуйста приложить примеры, о чем вы говорите?

**Comment by Delav-las-Kure** [comment]
Возможно идет речь об этом и эффекте мерцания при отрисовке страницы.
![image](https://user-images.githubusercontent.com/24542423/53565489-b45bd480-3b6a-11e9-9fca-de49bf692dc4.png)
