### ISSUE TITLE
Онлайн чаты. Нагруженность

### ISSUE THREAD

**Issue by dmitriitux** [anilibria/anilibria#32]
В данный момент чаты работают в режиме онлайн, с обновлением постоянным по протоколу HTTP. Вы делали стресс устойчивость чатов? сколько они выдержат нагрузки, есть технологии которые заменяют длинные запросы - это веб-сокеты. Может в их сторону посмотреть? :)

**Comment by poiuty** [comment]
Чат не используют, решили удалить https://github.com/anilibria/anilibria/commit/f42b4ede325824b6c635a89eb7c93edb69e324b4
 

Популярный фильтр <a href="https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt">ruadlist+easylis (adblock)</a> блокирует websocket.
```
$websocket,domain=...anekdot.ru|anilibria.tv|anime-rus.ru|animespirit.ru
```

Websocket используем в счетчике "смотрят". Когда заблокирован - xhr.

<img src="https://img.poiuty.com/img/d0/907b79df34eb6e0f104c338a42ee9bd0.png">
