### ISSUE TITLE
Верстка таблицами

### ISSUE THREAD

**Issue by dmitriitux** [anilibria/anilibria#33]
Верстка таблицами это устаревший метод. Сейчас верстают технологией flex. 
Вот краткое руководство по этой технологии: https://css-tricks.com/snippets/css/a-guide-to-flexbox/
Чтобы сделать мобильную версию надо убрать таблицы и перенести на флекс.

Так же у вас подключен бутстрап, там уже есть сетка.
https://getbootstrap.com/docs/3.3/css/#grid
Но это третий бутстрап (он у вас подключен), и там уже так же устаревший подход.

**Comment by Kirjaa** [comment]
В силу некоторых обстоятельств, дизайн взяли старый и сделали так. В будущем, дизайн будет изменен и все будет нормально свёрстано. Надеюсь, что это будущее будет совсем скоро.

**Comment by dmitriitux** [comment]
У вас есть дизайн? Я могу вам помочь с версткой, так же и с мобильной.
Так же вместо бустрапа предлагаю этот фреймворк использовать: https://getuikit.com/docs/introduction
Он навороченнее бустрапа и больше имеет преимуществ.

**Comment by Kirjaa** [comment]
Добавьте меня в телеграм @Kirjaa, там можно будет все обсудить.

**Comment by poiuty** [comment]
Пожалуйста, обсуждайте публично.

**Comment by Kirjaa** [comment]
Тогда скажу так: Нового дизайна ещё нет, но как только он будет готов, я с радостью выслушаю ваши идеи и пожелания по поводу вёрстки и использования фреймворков. Также, скорее всего потребуется помощь с мобильной версткой или наставления.

**Comment by vladimir908** [comment]
dmitriitux, с чего вы взяли что bootstrap плохой?)) Есть такое чудо как Material Design for Bootstrap

**Comment by dmitriitux** [comment]
> dmitriitux, с чего вы взяли что bootstrap плохой?)) Есть такое чудо как Material Design for Bootstrap

я не говорил, что он плохой, используется старый бутстрап, где сетка строится "float" подходом - это уже устаревший подход, сейчас уже все на флексах подобное делается :)
Но я лично считаю, что нет ничего лучше на данный момент uikit: https://getuikit.com
