### ISSUE TITLE
Обновите структуру данных для БД (main.sql)

### ISSUE THREAD

**Issue by buggyman** [anilibria/anilibria#35]
Опен-сорс, конечно, хорошо, но как можно что-то доработать на пустой базе данных? Положите в дерево исходников файл с тестовыми данными для БД. Сотню релизов плюс картинки обложек к ним должно быть достаточно. Можно фейковых, просто чтоб заработал тестовый сайт локальный...

**Comment by buggyman** [comment]
Попытался самостоятельно заполнить базу - пользователей создал, а вот при добавлении релизов (/pages/new.php) возникла ошибка:
```
[18-Feb-2019 09:53:08 Europe/Moscow] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'aname' in 'field list' in /opt/www/anilibria/anilibria/private/func.php:1241
Stack trace:
#0 /opt/www/anilibria/anilibria/private/func.php(1241): PDOStatement->execute()
#1 /opt/www/anilibria/anilibria/public/release/index.php(10): xrelease()
#2 {main}
  thrown in /opt/www/anilibria/anilibria/private/func.php on line 1241
```
В таблице xrelease нет поля aname - похоже, что и сама структура базы (файл sql/main.sql) на гитхабе в неактуальном состоянии...

**Comment by aaa4xu** [comment]
Хотя бы структуру БД обновите до актуального состояния, с тестовыми данными сами справимся 👌

**Comment by buggyman** [comment]
Снова структура БД потеряла актуальность...

**Comment by poiuty** [comment]
@buggyman, обновил https://github.com/anilibria/anilibria/commit/0339c496d70b00dc9885d4a7cf1597ec762371be
