### ISSUE TITLE
Сортировка завершенных релизов

### ISSUE THREAD

**Issue by Gravitir314** [anilibria/anilibria#36]
В сортировке релизов отсутствует возможность отсортировать по завершенным релизам.
https://prnt.sc/mkv84d

**Comment by buggyman** [comment]
Плюс на странице релиза больше не показывается статус (в работе / завершён). На старом сайте такая пометка была. Я смотрю только завершённые релизы, т.к. не люблю ждать выхода следующей серии; и теперь не знаю - можно ли начинать смотреть...

**Comment by Kirjaa** [comment]
В ближайшем будущем добавим статус релиза в сортировку и на страницу тайтла.
Когда точно это сделаем, пока сказать не могу, может через день, а может через неделю-две.

**Comment by Dimantchick** [comment]
Предложил бы просто помечать завершенные релизы минимально, но заметно, даже если не стоит сортировка "только завершенные". Например можно тонкую зеленую рамку или галочку в углу постера.

**Comment by poiuty** [comment]
https://github.com/anilibria/anilibria/commit/fae99ebf5a43e56c2fdf056576d00e0a596dc709
