### ISSUE TITLE
Как вы живёте без webpack?

### ISSUE THREAD

**Issue by j-heavy** [anilibria/anilibria#37]
С помощью webpack (с плагинами, офк) можно минифицировать HTML/CSS/JS, предоставляет нормальный tree-shaking для подключенных библиотек и многие другие плюшки для упрощения разработки и улучшения качества кода на выходе

**Comment by trueromanus** [comment]
Webpack хороший инструмент (и даже очень), но использовать его нужно ИМХО только на проектах с "толстым фронтом" т.е. там где очень много функционала на фронте вместе с такими фреймворками как Angular/React/Vue/Ember/<впишите свой>.
Более того для удобства создается так называемый "фронтовый проект" т.е. весь код связанный с фронтом оформлен в виде отдельного проекта и собирается и разрабатывается с использованием webpack.
Сейчас на сайте очень мало кода(я имею ввиду и js и css) на фронте, если его вынести в отдельный "фронтовый проект" там будет бледновато. Чтобы webpack раскрылся во всей красе нужно большой фронтовый проект, более того чтобы он был построен на базе одного из вышеупомянутый модно-молодежных фреймворков.
Я считаю что необходимость в применении таких инструментов как webpack настает в тот момент когда фронт на сайте распухает и становиться проблемой, а сейчас что-то мне подсказывает что это не так. Если забандлить текущий код (js/css) вместе с библиотеками (которые к слову минифицированы) то скорее всего разница будет мизерной, если вообще будет. А применение "плюшек для упрощения разработки" будет смазано из-за того что большая часть разработки ведется не на фронте.
Впрочем это сугубо мое мнение которое можно (и нужно :)) оспаривать.
P.S. И Ваше утверждение что webpack используется для "улучшения качества кода на выходе" некорректно. Единственный способ улучшить качество кода на выходе - улучшить качество кода на входе.

**Comment by j-heavy** [comment]
Webpack (или его аналоги) должен использоваться **всегда** (если сайт ~1kb то да, можно и без него обойтись), впрочем, так и делают, сейчас даже простые лендинги без него не обходятся. А то, что сейчас у Анилибрии — подход года так 2006 :D

Почему Webpack обязательно должен использоваться с "молодёжным фреймворком"? Серьезно, я не понимаю связь. Vue, React, Vanilla??? В Чём разница???

"Я считаю что необходимость в применении таких инструментов как webpack настает в тот момент когда фронт на сайте распухает и становиться проблемой" — фронт всегда проблема, судя по Анилибрии, серьёзная

"P.S. И Ваше утверждение что webpack используется для "улучшения качества кода на выходе" некорректно."
??? Autoprefixer, Babel transpiler, минификация и другое — не улучшения качества кода?

"вместе с библиотеками (которые к слову минифицированы)" — разработчики даже не удосужились убрать комментарии. Одной минификации недостаточно, особенно в 2к19, когда уже доступна технология нормального tree-shaking`a (которая, к слову, особо эффективна на том же бутстрапе)

"то скорее всего разница будет мизерной" — странно, я думаю по-другому: вебпак минифицирует всё, что можно, выпилит лишний код (включая подключенные библиотеки), при должной настройке dynamic imports дадут большой прирост к перфомансу, и да, с помощью webpack можно сжимать фотографии

**Comment by trueromanus** [comment]
"Webpack (или его аналоги) должен использоваться **всегда**"
При выборе технологий надо руководствоваться здравым смыслом, сайты разные бывают и инструменты им тоже нужны разные. Моя мысль в предыдущем комментарии была что все надо делать постепенно, по мере необходимости.

"Почему Webpack обязательно должен использоваться с "молодёжным фреймворком"? Серьезно, я не понимаю связь. Vue, React, Vanilla??? В Чём разница???"
Ну вообще я специально оставил там вариант "впишите свой" что означает не впишите свой любимый а буквально впишите свой. Я же Вам вроде не запрещаю писать на ванильном js и не говорю как Вы что кто-то что-то **должен** делать :). Написание сайта на ванильном js при разрастании также потребует от Вас создание локального фреймворка похожего на остальные и решающего схожие задачи, ну просто иначе никак. Да у него не будет имени и его нельзя будет выдернуть но он будет даже если такой задачи не ставилось :). Но опять же это только в том случае если задачи которые необходимо решать схожи (а в большинстве своем это так) с Vue/React и т.п.

"Autoprefixer, Babel transpiler, минификация и другое — не улучшения качества кода?"
А т.е. улучшение качества кода это минификация (которая просто уменьшает размер кода не меняя его) и инструменты которые обеспечивают backward-compability для тех ребят которые не обновляли свои браузеры года так с 2006. Видимо я что-то не понимаю в этой жизни :).

"странно, я думаю по-другому: вебпак минифицирует всё, что можно, выпилит лишний код (включая подключенные библиотеки), при должной настройке dynamic imports дадут большой прирост к перфомансу, и да, с помощью webpack можно сжимать фотографии"
Ну дак тут опенсорс же поэтому если Вы считаете что это пойдет на пользу проекту то никто Вам не мешает за пару вечерков оформить пул реквест где собрать весь фронт под крышей webpack и показать как делают ребята в 2019 году и насколько лучше данный подход. Хотя мне казалось что мы вот вот да и откажемся от бандлеров потому что данный функционал будет [нативно](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/import) в браузерах поддерживаться и можно пилить на ванильном js, но опять же backward-compability никто не отменял :).

"P.S. смотря на код: линтер бы не помешал :D"
Тут Вы бесспорно правы.

**Comment by j-heavy** [comment]
"При выборе технологий надо руководствоваться здравым смыслом, сайты разные бывают и инструменты им тоже нужны разные."
Хоть один кейс, где вебпак пошёл во вред, м (за исключение случаев, когда разрабы не могут в него, офк)?

"Хотя мне казалось что мы вот вот да и откажемся от бандлеров потому что данный функционал будет [нативно](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/import) в браузерах поддерживаться и можно пилить на ванильном js, но опять же backward-compability никто не отменял :)." & "...для тех ребят которые не обновляли свои браузеры года так с 2006"  — окей, я понял, на поддержку плевать. Ладно, это решение менеджмента, а не разработчиков

А т.е. улучшение качества кода это минификация (которая просто уменьшает размер кода не меняя его) — ну тут как посмотреть ИМХО :D Код энивей для пользователя лучше

**Comment by poiuty** [comment]
> цитата

ответ

**Comment by vladimir908** [comment]
Его к проекту на Django прикрутить возможно?
