### ISSUE TITLE
Быстрая загрузка торрент-файла

### ISSUE THREAD

**Issue by zigzar** [anilibria/anilibria#39]
Недоступна быстрая загрузка торрент-файла при наведении на блок последних вышедших серий
![button](https://user-images.githubusercontent.com/32038083/52792394-53b59d80-307c-11e9-90db-41cf81c9e012.png)

**Comment by Kirjaa** [comment]
Сделал.
Работает теперь так:
- Клик на весь элемент = переход на страницу релиза.
- Клик на кнопку скачать = скачивает залитый торрент.
