### ISSUE TITLE
Добавьте RSS 

### ISSUE THREAD

**Issue by Taraflex** [anilibria/anilibria#40]
Есть ли в планах добавить rss для ретроградов?
Желательно с прямыми ссылками на torrent файлы.

**Comment by AgentMC** [comment]
Я сделал свою версию RSS Анилибрии: https://getlibriarss.azurewebsites.net/api/RssOnline
Проверено в Thunderbird. Серии, вышедшие в октябре будет выдавать пачками, но за неделю должно прийти в норму. Обновляется раз в 15 минут. 
Если будут пожелалки или идеи - завтра залью код в свой гитхаб, можно будет создавать issue.

**Comment by AgentMC** [comment]
И ещё один апдейт: добавил ленту по торрентам: https://getlibriarss.azurewebsites.net/api/RssTorrent
@Degit22 я вижу, вы тоже лайкнули оригинал, так вот теперь RSS лента доступна.

**Comment by miroslim** [comment]
> И ещё один апдейт: добавил ленту по торрентам: https://getlibriarss.azurewebsites.net/api/RssTorrent
> @Degit22 я вижу, вы тоже лайкнули оригинал, так вот теперь RSS лента доступна.
Из-за вредительства роскомнадзора анилибрии пришлось поменять домен, так что ваши фиды больше не работают.
Очень печально. Я только обрадывался что нашел то что нужно, но роскомнадзор в очередной раз подложил свинью.

**Comment by AgentMC** [comment]
@miroslim только что проверил по https://blocklist.rkn.gov.ru/ , мои фиды не блокированы, ни по домену, ни по IP, и работают. Вы имеете в виду, что контент в фидах ссылается на `www.anilibria.tv` & `static.anilibria.tv`? Если есть альтернативный домен, я могу заменить. Если он работает так же. Ну или всегда давать ссылку на Анимепик. 
Этот фид вообще не ставит себе целью обходить блокировки, а просто информирует об обновлениях. Как бороться с РКН - это т.с. дело самих утопающих :)

**Comment by miroslim** [comment]
@AgentMC Вы все правильно поняли. 
Я пытался прикрутить вашу ленту к qBittorrent, но при попытке загрузки серий он спотыкался об ошибку связанную с доменом. Если бы вы поменяли домен на "dl0.anilib.top" (или "anilibria.anilibria.cf") то я был бы благодарен. 
Понятное дело что все время отслеживать состояние доменов вы не будете, и просить вас о таком нельзя, но я бы хотел верить что больше анилибрии бегать с одного домена на другой не придется. 
В крайнем случае просто придется пускать торрент-треккер через прокси или впн.

**Comment by vibos07** [comment]
@AgentMC привет! А ты сможешь сделать отдельную ветку рсс, в которой не будет ничего, кроме ссылки на обновленный торрент файл? Чтобы можно было этот фид добавить в торрент клиент на сервере и он автоматически выкачивал бы новые эпизоды по мере их выхода.

**Comment by dmitry-tomilov** [comment]
@vibos07 Получилось решить как-то данную проблему?

**Comment by T1MOXA** [comment]
> @AgentMC привет! А ты сможешь сделать отдельную ветку рсс, в которой не будет ничего, кроме ссылки на обновленный торрент файл (ну и названия релиза и его даты само собой)? Чтобы можно было этот фид добавить в торрент клиент на сервере и он автоматически выкачивал бы новые эпизоды по мере их выхода.
> 
> На данный момент из фида по торрентам клиент выкачивает страницы релизов, а не сами релизы, так как основной считается ссылка на сайт с описанием: ![Снимок экрана 2021-08-13 в 11 59 52](https://user-images.githubusercontent.com/31500117/129332785-33ab178e-e06b-4e8f-942f-c1d4c18bb19d.jpg)

https://rentry.co/oxiak#getrss
