### ISSUE TITLE
Письма уходят в спам

### ISSUE THREAD

**Issue by MaximKudryavtsev** [anilibria/anilibria#41]
Письма иногда попадают в спам из-за дефолтной php функции mail. Чтобы такого не случалось, предлагаю использовать php-mailer. Если нужно, то в выходные смогу кинуть PR

**Comment by poiuty** [comment]
Для отправки почты используем локальный smtp сервер (exim4). Настроен DKIM и SPF.
https://github.com/anilibria/docs/blob/master/install/exim.md

```
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@anilibria.tv header.s=mail header.b=fopQbpdu;
       spf=pass (google.com: domain of anilibria@anilibria.tv designates 37.1.217.18 as permitted sender) smtp.mailfrom=anilibria@anilibria.tv
```

Функция <a href="http://php.net/manual/ru/function.mail.php">mail()</a> передает данные на sendmail 
```
sendmail_cmd = sendmail_path;
```

```
#ifdef PHP_WIN32
	sendmail = popen_ex(sendmail_cmd, "wb", NULL, NULL);
#else
	/* Since popen() doesn't indicate if the internal fork() doesn't work
	 * (e.g. the shell can't be executed) we explicitly set it to 0 to be
	 * sure we don't catch any older errno value. */
	errno = 0;
	sendmail = popen(sendmail_cmd, "w");
#endif
	if (extra_cmd != NULL) {
		efree (sendmail_cmd);
	}
```
```
fprintf(sendmail, "To: %s\n", to);
fprintf(sendmail, "Subject: %s\n", subject);
if (hdr != NULL) {
	fprintf(sendmail, "%s\n", hdr);
}
fprintf(sendmail, "\n%s\n", message);
ret = pclose(sendmail);
```

письмо попадает в очередь `/var/spool/exim4/input`
SMTP отправляет его.


Обьясните, пожалуйста, почему письма попадают в спам?
Как php-mailer решает эту проблему?

**Comment by owner** [comment]
@poiuty, моя Яндекс.Почта видит, что письма приходят от имени `server.domain.com` и автоматом отправляет письмо в СПАМ независимо от того, что я нажал "Не спам". Посмотри в конфигах почты в `production` и чекни приход писем на Я.Почту и на Мейл.ру. В обоих случаях - летит в спам.

Если что - есть [mail-tester.com](https://mail-tester.com)

**Comment by MaximKudryavtsev** [comment]
@poiuty честно говоря никогда вникал в тонкости, почему mail работает через раз, вот есть объяснение [https://toster.ru/q/110941](url). А phpmailer отправляет емейл с реального ящика через SMTP

**Comment by poiuty** [comment]
@owner, спасибо.

Проверил mail-tester.com, `server.domain.com` пока не нашел.

https://img.poiuty.com/img/2b/5f94ce7d61d3c12814ec6f963462b12b.png
https://img.poiuty.com/img/94/990720c050e66bb75514664dcdef5294.png

```
From : AniLibria <webmaster@anilibria.tv>	
Bounce address : anilibria@anilibria.tv
```

**Comment by poiuty** [comment]
https://img.poiuty.com/img/94/990720c050e66bb75514664dcdef5294.png
helo=server.domain.com

Поправил.
```
# hostname anilibria.tv
# nano nano /etc/hostname
anilibria.tv

# /etc/init.d/exim4 restart
```

Проверил.
https://img.poiuty.com/img/a6/a412ac37cfbc793bfa6c28ca625242a6.png
helo=anilibria.tv

Спасибо.

**Comment by buggyman** [comment]
```
# host 37.1.217.18
Host 18.217.1.37.in-addr.arpa. not found: 3(NXDOMAIN)
```

Ещё желательно прописать PTR (такой же - anilibria.tv) для IP отправителя (37.1.217.18). Это надо хостера просить об этом. До сих пор встречаются конфигурации (обычно у университетов всяких), которые не принимают почту если нет PTR. Да и публичные почтовые сервисы будут давать больше баллов таким письмам.

Если же всё-равно письма будут в спам попадать, то можно сделать отправку через почтовики яндекса (раз уж у вас MX на них указывает). Т.е. экзиму указать смарт-хостом их сервера, плюс логин-пароль.

**Comment by poiuty** [comment]
PTR 
```
host 37.1.217.18
18.217.1.37.in-addr.arpa domain name pointer anilibria.tv.
```

**Comment by poiuty** [comment]
@owner, проверил яндекс почту - попадает в папку входящие.

**Comment by owner** [comment]
@poiuty, молодец. Теперь почта не будет попопадать в спам.
