### ISSUE TITLE
Слетает авторизация

### ISSUE THREAD

**Issue by buggyman** [anilibria/anilibria#42]
Постоянно слетает авторизация. Подозреваю, что дело в отсутствии указания времени истечения у сессионной куки:
```
set-cookie: PHPSESSID=..............; path=/; domain=www.anilibria.tv; secure; HttpOnly
```
А может и на сервере удаляются сессионные файлы(?)...

**Comment by poiuty** [comment]
Думаю, исправили https://github.com/anilibria/anilibria/commit/1fae52676273c608f9a959f56be71ac637662f4d
