### ISSUE TITLE
Переход от функционального к ООП.

### ISSUE THREAD

**Issue by Asethon** [anilibria/anilibria#47]
И так.
Большая часть кода проекта - кучка функций, раскиданных по файлам(которые, в итоге, бездумно везде инлкюдятся).

1. Включить в проект composer и использовать его систему автоподгрузки классов.
2. Разложить функции по соответствующим их назначению классам и внедрять понемногу паттерн MVC.
3. Не критично, но у вас файл index.php является инициализирующим страницы.
Уберите html/css в шаблон, как сделано на остальных страницах.
4. Не используйте системные PHP-классы(Memcached, PDO. Последнее особенно).
Подключите соответствующие библиотеки через composer. А автоподгрузка всё остальное сделает за вас.

5. К коду нужны комментарии. Иногда я натыкаюсь на набор еле читаемого кода и пытаюсь понять, кто я, что я делаю не этой планете и почему я не 2д. Это поможет другим разработчикам и вам, в итоге.

Внедрять композер я уже [начал](https://github.com/Asethon/anilibria), но сейчас [занимаюсь](https://github.com/Asethon/AniDocker) написанием docker-образов для разворачивания сайта локально без установки на сам пк лишних вещей.

6. Не используйте структуру один файл - одна страница.
Стоит переписать на систему роутинга с паттерном MVC и автогенерацией страниц с последующим кэшированием содержимого, при необходимости.

**Comment by Asethon** [comment]
7. И не стоит злоупотреблять глобальными переменными.
(После внедрения composer'а от этого можно будет избавиться).

**Comment by aaa4xu** [comment]
@Asethon предлагаю начать с попытки пропихнуть через пул реквесты минимальный коммит:
- `composer.json` с указанием требуемой версии php и расширений + `composer.lock`
- Подключение `autoload.php` в точках входа в приложение
Этот коммит позволит понять насколько больно будет его интегрировать как в код, так и в процесс его развертывания.

**Comment by Asethon** [comment]
composer.lock, как и вся папка vendor, должны быть в гитигноре.
К утру займусь этим. Хорошее предложение. Если пулл-реквест будет принят - предложу ещё некоторые изменения, не затрагивающие проект глобально.

**Comment by aaa4xu** [comment]
> composer.lock, как и вся папка vendor, должны быть в гитигноре.

`vendor` должен быть заигнорен, а вот `composer.lock` - нет. [Из документации](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control) Composer:

> Committing this file to VC is important because it will cause anyone who sets up the project to use the exact same versions of the dependencies that you are using. Your CI server, production machines, other developers in your team, everything and everyone runs on the same dependencies, which mitigates the potential for bugs affecting only some parts of the deployments.

**Comment by Asethon** [comment]
Хорошо. Приму к сведению.

**Comment by poiuty** [comment]
> Не используйте системные PHP-классы(Memcached, PDO. Последнее особенно).

Судя по этому коммиту https://github.com/Asethon/anilibria/commit/f0cf792fc189ebe0396ecbb1b43bb957a39ef4a7, вы предлагаете использовать <a href="https://github.com/clickalicious/memcached-php">clickalicious/memcached-php</a>

Приведите, пожалуйста, аргументы. Почему мы должны отказаться от использования
http://php.net/manual/ru/book.memcached.php
http://php.net/manual/ru/book.pdo.php

**Comment by Asethon** [comment]
> > Не используйте необходимые PHP-классы (Memcached, PDO. Последнее особенно).
> 
> [Asethon @ f0cf792](https://github.com/Asethon/anilibria/commit/f0cf792fc189ebe0396ecbb1b43bb957a39ef4a7) , вы предлагаете использовать [clickalicious / memcached-php](https://github.com/clickalicious/memcached-php)
> 
> Приведите, пожалуйста, аргументы. Мы Должны почему Отказаться от Использования 
> [http://php.net/manual/ru/book.memcached.php ](http://php.net/manual/ru/book.memcached.php)
> http://php.net/manual/ru/book.pdo.php

Рекомендуется использовать любой класс, реализующий работу с кэшем, если он так же реализует интерфейс по стандарту PSR-6 или более новый PSR-16.

Напрямую работать с PDO не стоит по схожим причинам. Используйте библиотеки, взаимодействующие с PDO, чтобы, при необходимости, переход на другую БД был максимально безболезненным.

**Comment by poiuty** [comment]
@Asethon, спасибо.
Мы используем mysql (mariadb). Не планирую переход на другю DB.
Статистику работы базы можно посмотреть по ссылкам
http://anilibria.tv:85/db-day.html
http://anilibria.tv:85/mysql-day.html

> Рекомендуется использовать любой класс, реализующий работу с кэшем, если он так же реализует интерфейс по стандарту PSR-6 или более новый PSR-16.

Не вижу смысла подключать дополнительный код, который реализует функционал memached <a href="http://php.net/manual/ru/memcached.get.php">get</a> и <a href="http://php.net/manual/ru/memcached.set.php">set</a>
```php
$a = $cache->get('x');
if($a === false){
	...
	$cache->set('x', 'result', 300);
}
```

**Comment by Asethon** [comment]
> @Asethon, спасибо.
> Мы используем mysql (mariadb). Не планирую переход на другю DB.
> Статистику работы базы можно посмотреть по ссылкам
> http://anilibria.tv:85/db-day.html
> http://anilibria.tv:85/mysql-day.html
> 
> > Рекомендуется использовать любой класс, реализующий работу с кэшем, если он так же реализует интерфейс по стандарту PSR-6 или более новый PSR-16.
> 
> Не вижу смысла подключать дополнительный код, который реализует функционал memached [get](http://php.net/manual/ru/memcached.get.php), [set](http://php.net/manual/ru/memcached.set.php)
> 
> ```
> $a = $cache->get('x');
> if($a === false){
> 	...
> 	$cache->set('x', 'result', 300);
> }
> ```

С таким же успехом, можно оставаться на php 5.6 и пользоваться IE.
Есть стандарты и их рекомендуется, хоть и не обязательно, соблюдать.
В зависимости от их соблюдения(в данный момент я про PSR-ы), люди либо будут иметь желание поддерживать ваш код и помогать в разработке функционала, либо не будут хотеть разбираться в наборе функций, раскиданных по файлам.

Игнорируя это - вы игнорируете всё сообщество PHP и его стремление к избавлению от неподдерживаемого кода.

**Comment by poiuty** [comment]
@Asethon, мы используем php 7.3, в коде нет deprecated functions.
pdo и memcached стандартный функционал.

Если нет других аргументов, то я не буду накачивать код зависимостями вроде 
memcached => https://github.com/clickalicious/memcached-php
mail https://github.com/anilibria/anilibria/issues/41 => https://github.com/PHPMailer/PHPMailer

**Comment by Asethon** [comment]
> @Asethon, мы используем php 7.3, в коде нет deprecated functions.
> pdo и memcached стандартный функционал.
> 
> Если нет других аргументов, то я не буду накачивать код зависимостями вроде
> memcached => https://github.com/clickalicious/memcached-php
> mail #41 => https://github.com/PHPMailer/PHPMailer

memcached и есть зависимость.
Прочитай, что такое PSR и для чего они нужны.
То, что в проекте используется свежая версия PHP - это хорошо.
Только вот код времён динозавров. Более того, он абсолютно не читаемый и состоит из кучи подключаемых функций.
Про логирование молчу (мало того, что не указывается где конкретно возникла ошибка, так ещё и пишется не в файл с расширением .txt).

**Comment by aaa4xu** [comment]
Давайте отставим в сторону вопрос с PDO и сконцентируемся пока на Memcached.

Как было указано выше, существует два стандарта для кешей – PSR-6 и PSR-16. Давайте определимся с тем, о каком именно мы говорим. Мое мнение – требуется использовать PSR-16, т.к., во-первых, он ближе к используемому сейчас интерфейсу, а, во-вторых, не имеет проблем с хранением null в качестве значения.

Я вижу следующие преимущества перехода на PSR-совместимый интерфейс вместо стандартного для Memcached:
* Сейчас все библиотеки и фреймворки стараются быть совместимыми с PSR, отсюда, получаем два преимущества: 
  * Новый человек скорее всего уже знаком с PSR-совместимым интерфейсом и ему требуется меньше времени для понимания кода
  * Если, в будущем, какая-то из подключаемых библиотек будет требовать доступ к кешу, ожидать она будет именно PSR-совместимый кеш.
* Т.к. мы закрепим интерфейс, мы сможем менять реализацию кеша на другие совместимые с этим PSR. Если это кажется сейчас бессмысленным, то вот пример замены, когда это потребуется в ближайшее время: тесты. Поднимать memcache, да и вообще зависеть тестами от него – плохая идея, а переход на PSR-16 позволит использовать in-memory реализацию во время тестирования.

**Comment by poiuty** [comment]
@Asethon, пожалуйста, не указывайте мне, что делать.

@aaa4xu, не вижу причин менять memcached на аналог.

Если человек хочет развернуть локально, то может обратиться к документации.
https://github.com/anilibria/docs/tree/master/install

Приветствую идею поместить все в докер. 
https://github.com/anilibria/docs/issues/1

**Comment by buggyman** [comment]
Предлагаю начать с самого необходимого - переход на классы, паттерн MVC и роутинг. По этим пунктам возражений у разработчиков нет?
А с остальным будет видно дальше, по ходу роста проекта.

**Comment by poiuty** [comment]
@buggyman, 

> переход на классы, паттерн MVC и роутинг

Сделал отдельную ветку. Пожалуйста, присылайте pr.
https://github.com/anilibria/anilibria/tree/OOP

**Comment by Asethon** [comment]
> @buggyman,
> 
> > переход на классы, паттерн MVC и роутинг
> 
> Сделал отдельную ветку. Пожалуйста, присылайте pr.
> https://github.com/anilibria/anilibria/tree/OOP

По поводу роутинга: необходимо выбрать библиотеку, реализующую его. Самим писать нет никакой надобности(они везде практически идентичны).
А так же вариацию хранения роутов.


Я за роутинг от symfony и использование .yml-файлов в качестве хранилища роутов. Жду ваших вариантов.

Документация на русском:
https://symfony.ru/doc/current/routing.html

**Comment by buggyman** [comment]
> Я за роутинг от symfony и использование .yml-файлов в качестве хранилища роутов. Жду ваших вариантов.

Имхо это оверхед, я бы предпочёл что-нибудь попроще. Навроде FastRoute - https://github.com/nikic/FastRoute

**Comment by shindakioku** [comment]
Парни, у вас джс 2007го года
А про пхп я вообще молчу

Мой вам совет - возьмите готовую вещь и перепишите
Ваше внедрение MVC паттерна закончится плачевно.

**Comment by shindakioku** [comment]
@buggyman я тебя слушаю :)

**Comment by dmitriitux** [comment]
Внесу свою маленькую лепту, чтобы не морочиться, можно просто взять Zend Framework 3 :)
