### ISSUE TITLE
Баг плеера Анилибрии на iOS

### ISSUE THREAD

**Issue by zigzar** [anilibria/anilibria#50]
При попытке развернуть на полный экран плеер Анилибрии на iOS происходит вот такая картина:

![c2pix2vnqqe](https://user-images.githubusercontent.com/32038083/53055742-de9dfa00-34b9-11e9-8a46-0b390e76e7a7.jpg)

Проверял на iPhone 6 и iPad 3

**Comment by poiuty** [comment]
Написал в поддержку playerjs.com, получил ответ.
> Похоже на какой-то конфликт с вашими скриптами, так как полная копия плеера на пустой странице открывается нормально. Будем признательны, если найдете причину. 

Проблема возникает, когда добавляем z-fix (выключить/ включить свет)
https://img.poiuty.com/img/62/ca33845cf5437a90d9fb4d241b77d562.png
https://github.com/anilibria/anilibria/blob/master/css/main.css#L679-L682
```
.z-fix {
	position: relative;
	z-index: 999;
}

<div class="xplayer z-fix" id="anilibriaPlayer"></div>
```

**Comment by poiuty** [comment]
Поправил https://github.com/anilibria/anilibria/commit/0840566804b347a5ec78c234fbac99ba6f2f40bc
