### ISSUE TITLE
bootstrap порезан?

### ISSUE THREAD

**Issue by buggyman** [anilibria/anilibria#58]
Попытался сделать [dropdown через бутстрап](https://getbootstrap.com/docs/3.3/components/#dropdowns) и обнаружил, что он не работает: нет нужных стилей в файле css/bootstrap.min.css. Вы его нарочно порезали? Каков алгоритм действий, если он нужен?

P.S.: насчёт ненужности выпадашек - на странице поиска переключалка **Популярное/Новое** в текущем виде непонятно выглядит, многие посетители не находят как посмотреть новые релизы (где-то в комментариях видел такие вопросы). Выпадашкой, либо [btn-groups](https://getbootstrap.com/docs/3.3/components/#btn-groups) было бы интуитивно понятней.

Плюс ещё есть пара идей для dropdowns.

**Comment by poiuty** [comment]
https://getbootstrap.com/docs/3.4/customize/

**Comment by buggyman** [comment]
@poiuty 
А где взять config.json с текущими настройками? Или инструкции - какие галочки снять чтоб добавить только нужное и при этом ничего не сломать?

**Comment by owner** [comment]
> 
> 
> @poiuty
> А где взять config.json с текущими настройками? Или инструкции - какие галочки снять чтоб добавить только нужное и при этом ничего не сломать?

Его нигде не надо брать. Это модифициранный Bootstrap. Основу для своих разработок можете взять по ссылке: `https://www.anilibria.tv/css/bootstrap.min.css`

**Comment by buggyman** [comment]
@owner 
Вы предлагаете вручную искать какие стили и код яваскрипт вставить/убрать в/из минифицированных файлов? И потом, принимая пул-риквест от сторонних разработчиков, вы каждый раз так же вручную будете проверять, не добавили ли они чего лишнего и всё ли убрали/добавили? В \_минифицированных\_ файлах?

Мне кажется, что через какое-то время это выйдет из под контроля. Не лучше ли сразу положить в проект config.json, который скачивается вместе с модифицированным бутсрапом? Это позволит в любой момент легко перегенерировать файлы, в том числе и для обновления версии бутстрапа (у вас сейчас версия 3.3.7, а на сайте у них - 3.4.1).

**Comment by owner** [comment]
> 
> 
> @owner
> Вы предлагаете вручную искать какие стили и код яваскрипт вставить/убрать в/из минифицированных файлов? И потом, принимая пул-риквест от сторонних разработчиков, вы каждый раз так же вручную будете проверять, не добавили ли они чего лишнего и всё ли убрали/добавили? В _минифицированных_ файлах?
> 
> Мне кажется, что через какое-то время это выйдет из под контроля. Не лучше ли сразу положить в проект config.json, который скачивается вместе с модифицированным бутсрапом? Это позволит в любой момент легко перегенерировать файлы, в том числе и для обновления версии бутстрапа (у вас сейчас версия 3.3.7, а на сайте у них - 3.4.1).

Как угодно.
