### ISSUE TITLE
Как я вижу скелет ООП-части кода

### ISSUE THREAD

**Issue by Asethon** [anilibria/anilibria#65]
Прошу обратить внимание на всё, что находится в папке `App` моего форка данного репозитория.

https://github.com/Asethon/anilibria/tree/feature/oop/App

Помимо валидации, сама сущность(Entities) и частично фабрика, репозиторий и сервис для релизов я описал и буду писать ООП в таком стиле.

Так же, я сделал репозитории как для работы с EasyDb, так и напрямую с PDO, так что вы спокойно сможете заменить одно на другое не переписывая практически ничего(одну строчку).
Ну и, естественно, можно будет добавить свои реализации репозитория, используя интерфейс **`ReleaseRepositoryInterface`**.

Для репозитория обязательным параметром является класс кэша, реализующий интерфейс **`CacheInterface`** по стандарту PSR-16. Для `Memcached` такой тоже есть, так что проблем возникнуть не должно.

Фабрика буквально собирает Release из полученных данных, а так же из объектов-значений **`Name`**, **`Descriptions`** и **`Team`**, где хранятся более-менее взаимосвязанные переменные, дабы не перегружать основной класс **`Release`**

Как-то так, короче говоря.
Это, естественно, не финальные версии данных классов, однако, общее представление о моём взгляде на ООП вы можете получить.
Жду критики, предложений и т.д. и т.п.

**Comment by RadiationX** [comment]
На мой взгляд, выглядит неплохо.

**Comment by buggyman** [comment]
А зачем нужны эти фабрики и сущности? Имхо - только лишняя прослойка. Почему бы не работать напрямую с массивом, который пришёл от SELECT? И что если у меня составной SELECT с несколькими полями из нескольких таблиц?

Видел такой подход, когда дорабатывал проект на symfony, но так и не понял его преимуществ.

**Comment by Asethon** [comment]
@buggyman, по твоим словам у меня складывается ощущение, что именно ты и написал тот бардак, что сейчас есть в проекте.
Изучи DDD, DI в частности, и ООП в целом.

**Comment by buggyman** [comment]
@Asethon, вам нужно обосновать свой подход тем людям, которые написали этот бардак. Внятно, а не в таком духе. Вряд ли они примут ваши правки только потому, что это модно-молодёжно. Имхо, конечно.

**Comment by aaa4xu** [comment]
`ReleaseRepositoryInterface`:
- Метод для обновления релиза?
- Для размышлений: Внутри Repository находится метод setRepository который принимает драйвер БД.
- Мой PHPStorm ругается на то, что `getRelease(int $id)` дает `getRelease(\App\Interfaces\int $id)` из-за чего все реализации не совместимы с интерфейсом.
- Не вижу метода для получения нескольких результатов сразу
- Не вижу метода для получения результата по `code`

`ReleasePdoRepository`:
- Для размышлений: Что-то явно не так с методами `setDb` и `setRepository`
- Почему `ReleasePdoRepository` принимает кеш в качестве аргумента а для БД у него отдельный сеттер?
- Запрос в `addRelease` строится прям очень плохо

`ReleaseEasyDbRepository`:
- Для размышлений: Много кода дублируется с `ReleasePdoRepository`

`ReleaseFactory`:
- Почему метод называется `addRelease`? Куда он его добавляет?
- Почему и зачем фабрика хранит какой-то кусок данных последнего созданного ей релиза?

`Team`:
- `namespace Ap\Entities`;

По дублированию кода в `ReleaseEasyDbRepository`/`ReleasePdoRepository`, возможно, имеет смысл завести декоратор который сам будет реализовывать `ReleaseRepositoryInterface`, и при этом принимать в себя объект реализующий `ReleaseRepositoryInterface` и брать на себя всю работу с кешем, таким образом в Repository останется только работа с БД.

**Comment by Asethon** [comment]
@aaa4xu , `setRepository` - временное решение, и я от него [избавился](https://github.com/Asethon/anilibria/commit/b36163019031bf8f088c3772697605e1a29d43d5)

**Comment by Asethon** [comment]
@aaa4xu , [переименовал метод фабрики](https://github.com/Asethon/anilibria/commit/183948a4de93d113937ea2a34d4dcf32fcf12b22)

**Comment by Asethon** [comment]
> По дублированию кода в `ReleaseEasyDbRepository`/`ReleasePdoRepository`, возможно, имеет смысл завести декоратор который сам будет реализовывать `ReleaseRepositoryInterface`, и при этом принимать в себя объект реализующий `ReleaseRepositoryInterface` и брать на себя всю работу с кешем, таким образом в Repository останется только работа с БД.

@aaa4xu , надеюсь, я тебя правильно понял и [написал](https://github.com/Asethon/anilibria/blob/feature/oop/App/Repositories/ReleaseCacheDecorator.php) именно то, что необходимо в данном случае ([все изменения по этому поводу](https://github.com/Asethon/anilibria/commit/03830e5f22004bfee58910cdc652f25643416525))

**Comment by shindakioku** [comment]
@Asethon всего пару вопросов:
а) Зачем ты делаешь интерфейсы на репозитории?
Тебе рассказать какой % того, что проект меняет свою ORM/базу данных и прочее?
(Не трать свои силы на рассказ о безболезненной миграции при изменение хранилища. Тебе придется просто написать заново реализацию, все...Собсна, профита от этого интерфейса 0.)

б) https://designpatternsphp.readthedocs.io/ru/latest/Structural/DataMapper/README.html
Посмотри на свои сущности, пожалуйста.
А спустя внедрения нескольких бизнес фич глянь на свой код вместе с фабриками.

https://github.com/Asethon/anilibria/blob/feature/oop/App/Repositories/PDO/ReleasePdoRepository.php#L17
DI (dependency injection)?

https://github.com/Asethon/anilibria/blob/feature/oop/App/Repositories/ReleaseCacheDecorator.php
Нене, пагади.
1ое) Это уже никакой не Cache 
2ое) На декоратор это тоже уже не тянет


https://github.com/Asethon/anilibria/blob/feature/oop/App/Services/ReleasesService.php#L36
В чем смысл таких сервисов-делегаторов?

**Comment by Asethon** [comment]
@shindakioku, я ничего против критики не имею. Даже наоборот.
Приношу тебе искреннюю благодарность за данный комментарий.

В течении дня постараюсь ответить на твои вопросы и исправить указанные ошибки, либо объясню, почему я сделал именно так, если будет необходимость в этом.

**Comment by Asethon** [comment]
> а) Зачем ты делаешь интерфейсы на репозитории?
Банальный пример - юнит-тесты. Ну и для работы декоратора. Без общего с репозиториями интерфейса он не будет работать.

> https://github.com/Asethon/anilibria/blob/feature/oop/App/Repositories/ReleaseCacheDecorator.php
Нене, пагади.
1ое) Это уже никакой не Cache
2ое) На декоратор это тоже уже не тянет

Честно говоря, я не вижу тут ошибки.
Декоратор дополняет функционал репозиториев. И занимается кэшированием(нет кэша - создаёт объект), а репозитории только общаются с базой данных. Хотя я и вижу очевидную проблему: мне приходится разделять общий интерфейс на частные: для репозиториев и для декоратора.
Если у тебя есть идея, как реализовать это лучше - буду рад, если хотя бы направишь в нужную сторону.

> б) https://designpatternsphp.readthedocs.io/ru/latest/Structural/DataMapper/README.html
Посмотри на свои сущности, пожалуйста.
А спустя внедрения нескольких бизнес фич глянь на свой код вместе с фабриками.

Тут согласен. Однако, я не придумал ещё, как применить тут паттерн DataMapper. Сказывается недостаток работы с подобного рода вещами.
