### ISSUE TITLE
WebSocket стучится в локалхост

### ISSUE THREAD

**Issue by TerisbackDev** [anilibria/anilibria#69]
![image](https://user-images.githubusercontent.com/26527529/53514989-cbf37880-3aea-11e9-9d38-92a6b49ee83e.png)

**Comment by TerisbackDev** [comment]
Так и должно быть?

**Comment by poiuty** [comment]
reload.js - внешний скрипт. 
https://github.com/anilibria/anilibria/search?q=reload.js&unscoped_q=reload.js

Думаю, связано с видеорекламой. 
Напишите, пожалуйста, полный адрес.

**Comment by TerisbackDev** [comment]
Я наверное далёк, но ссылку на страницу где словил?
Вот [https://www.anilibria.tv/release/dororo.html](Dororo)
![image](https://user-images.githubusercontent.com/26527529/53544589-68983380-3b48-11e9-9ebf-3332189ba1cb.png)

**Comment by TerisbackDev** [comment]
Извиняюсь, это видимо одно из расширений
