### ISSUE TITLE
Поиск по "статусу" релиза ("в работе", "завершённые", "есть концовка"

### ISSUE THREAD

**Issue by LupinTv** [anilibria/anilibria#70]
1) Добавить в выбор флажков "есть концовка" (для тех аниме, у которых полноценная или хотя бы адекватная филлерная концовка, а не "открытая, читайте дальше в манге")
2) Вывести фильтр со статусами в каталоге (https://www.anilibria.tv/pages/catalog.php)

Название статуса "есть концовка", можно поменять на "законченное", если статус "завершённое" заменить на "доделанное". Короче говоря, нужно максимально понятное определение по статусам.

Суть в том, что статус "завершённое" -- сейчас означает, что наша озвучка сделана до конца. Однако, если пользователь хочет посмотреть ДЕЙСТВИТЕЛЬНО законченное произведение (пример: Токийский Гуль 3, Шарлотта, Ангельские Ритмы) -- ему бы пригодилась функция, помогающая находить такие.

**Comment by buggyman** [comment]
Если я правильно понял мысль в п.1, то можно сделать как на lostfilm.tv:
Статус:
- Между сезонами
- Будет объявлено
- Идет 3 сезон
- Завершен

Только у вас сезоны сделаны раздельно, менять во всех статусы вручную будет муторно. Нужно сделать привязку в БД (а заодно это можно использовать для автоматической генерации ссылок на другие сезоны - сейчас далеко не всегда они есть).

**Comment by LupinTv** [comment]
Нет, на лосте такой функции нет ("есть концовка"), там она и не нужна. Большинство сериалов -- завершены (исключая "визитёров" и подобные, которые закрыли без адекватной концовки, т.к. не окупились). В аниме же всё ОЧЕНЬ ПЛОХО в этом плане, огромный процент аниме = реклама манги или ранобэ без адекватной или хотя бы внятной концовки. Так что такая функция будет новаторской (её нет НИГДЕ!) и, вероятно, востребованной.

**Comment by shindakioku** [comment]
@LupinTv Спасибо, схоронил!

**Comment by poiuty** [comment]
https://github.com/anilibria/anilibria/commit/fae99ebf5a43e56c2fdf056576d00e0a596dc709
