### ISSUE TITLE
Портфолио для войсеров

### ISSUE THREAD

**Issue by LupinTv** [anilibria/anilibria#73]
Портфолио для войсеров - примерное ТЗ. Предложения по улучшению - принимаются.

![prototype_portfolio_voicers](https://user-images.githubusercontent.com/22909560/53565841-9e9adf00-3b6b-11e9-8f54-1d8575a93622.jpg)

"Александр Парфёнов

Творческий псевдоним: Lupin

В сфере озвучания: с августа 2010
В команде AL: с апреля 2012"

Эти поля заполняются вручную.

"Озвучено на AL: 83 тайтла
|> СЭМПЛ ГОЛОСА"

83 тайтла = информация из бд
сэмпл голоса = залитый файл .mp3 (не больше 2 мин.)

Фильтр -- по полю "озвучка". Внешний вид -- не плиткой, а списком для портфолио больше подходит. Естественно, данный макет - тестовый, нужно сначала нарисовать полноценный дизайн.

**Comment by Asethon** [comment]
@LupinTv, создать отдельную таблицу с командой Анилибрии и привязывать к релизами список из этой таблица, а не текст. На странице с добавлением/редактированием релиза будет не текстовое поле, а выпадающий список, где можно будет выбрать людей из команды.
И по этому полю фильтровать и выводить в портфолио список релизов.

Улучшение бизнес-логики. В ООП-версии уже реализовываю указанную возможность.

**Comment by Kirjaa** [comment]
@Asethon, по тексту также можно отфильтровать -> SELECT * FROM `xreleases` WHERE `voice` LIKE '%Lupin%';
Но с базой войсеров идея тоже не плохая.

**Comment by Kirjaa** [comment]
@LupinTv я могу это сделать, я так понимаю ты хочешь это отдельной страницей ?

**Comment by Asethon** [comment]
@Kirjaa, не знаешь, может ли один и тот же человек из команды Анилибрии выполнять функции сразу двоих людей(войсер и таймер и прочие комбинации)?
А то я не знаю, как лучше построить структуру класса(и аннотаций, на основе которых таблица генерируется).

**Comment by Kirjaa** [comment]
@Asethon сори что раньше не заметил, да, может.

**Comment by AgentMC** [comment]
@Kirjaa @LupinTv  теперь после https://youtu.be/atHeLek4V3o?t=780 эта страница должна быть непубличной?
