### ISSUE TITLE
Будет тёмная тема?

### ISSUE THREAD

**Issue by Terisback** [anilibria/anilibria#74]
# [Видео с концептом](https://youtu.be/ZKw1Qo9ycN8)
![screenshot_1](https://user-images.githubusercontent.com/26527529/53578066-acb32480-3b98-11e9-95c8-1b4ab8671f00.png)
![screenshot_2](https://user-images.githubusercontent.com/26527529/53578068-ae7ce800-3b98-11e9-853f-a3f126aebf40.png)

**Comment by TerisbackDev** [comment]
Моя репа с темой для Stylus
https://github.com/TerisbackDev/AniLibria-Dark-Theme

**Comment by Rikonardo** [comment]
Моё расширение для оперы.
https://addons.opera.com/be/extensions/details/anilibria-dark/
