### ISSUE TITLE
Кнопка "Сообщить об ошибке"

### ISSUE THREAD

**Issue by buggyman** [anilibria/anilibria#78]
Не хватает обратной связи с владельцами сайта, чтобы сообщить об ошибках в оформлении релизов. Комментарии редакторы не всегда читают, особенно в старых релизах.

Примеры:
https://www.anilibria.tv/release/atom-the-beginning.html - в русском названии буква в конце отстуствует
https://www.anilibria.tv/release/alice-or-alice.html - в торренте на 8-ой серии первой идёт оригинальная озвучка, так что на телике подхватывается она. В остальных сериях идёт сначала русская дорожка.

Саму кнопку я почти доделал, потестировать можно тут: http://ani.master.2nt.ru/pages/catalog.php
Логин/пароль:
admin/admin  (access=3)
123/123
user/user
test/test

Если есть пожелания по функционалу - оставляйте в этой теме.

**Comment by Kirjaa** [comment]
При появлении модального окна контент на пару пикселей сдвигается, при исчезновении возвращается обратно.

**Comment by buggyman** [comment]
@Kirjaa - это общая проблема на сайте анилибрии (нажмите на текст "Работа над релизом" на странице любого релиза).

https://www.anilibria.tv/css/main.css строка 227:
```
.modal-open {
    padding-right: 0px !important;
}
```
^^ так пофиксили другую проблему при появлении бутстраповской модалки.

**Comment by OmlineEditor** [comment]
Предлагаю цвет кнопки сделать красного оттенка, чтобы она выделялась на общем фоне.
Также можно вести учет кто сколько нашел ошибок в аниме и кто прислал больше всего исправлений в этом месяце получает похвалу от люпина в ЛЛН или медальку в виде картинке или определнные статус аккаунта. Это сподвигнет людей к поиску косяков и улучьшит качество аниме.
![color](https://user-images.githubusercontent.com/13348933/55963565-c063a780-5c7b-11e9-8a62-126492395796.png)

**Comment by buggyman** [comment]
Отбой. Люпин на стриме сказал, что сайту не нужны новые функции - люди будут путаться.

**Comment by OmlineEditor** [comment]
Вы серьезно? Как вам сообщать что вы напортачили? Вы не читаете все комментарии, если что-то не так нет обратной связи. Писать вам в ВК? Но Люпин на половыну сообщений не отвечает. Как одна кнопка может запутать пользователей?
Ваш начальник ведет вас в тупик, я это вижу со стороны, ваш сайт развивается не в том направлении.
Подумайте еще раз!

**Comment by poiuty** [comment]
Готово https://github.com/anilibria/anilibria/commit/b3d76be1ba90f63855f575a293ab0b588c1ab3a9
