### ISSUE TITLE
Реальное значение людей кто смотрит аниме в онлайне

### ISSUE THREAD

**Issue by OmlineEditor** [anilibria/anilibria#87]
На странице аниме пишут кто смотрит аниме, но это число не показывает сколько людей смотрит аниме в онлайне, это число людей открывшиш просто эту страницу.
Создается ложное представление о реальном количестве людей кто смотрит это аниме.
Можно это исправить?
![see](https://user-images.githubusercontent.com/13348933/55888509-2686f680-5bb8-11e9-9e7b-2eeee8bb6a8a.PNG)

**Comment by maxqwars** [comment]
Зачем?

**Comment by mishailovich** [comment]
> Зачем?

Чтобы знать сколько сейчас людей смотрит Наруто 🤪
