### ISSUE TITLE
Некоторые вопросы по поводу полей в базе данных

### ISSUE THREAD

**Issue by Asethon** [anilibria/anilibria#89]
@poiuty , доброго времени суток.
Если не сложно, мог бы ты объяснить назначение следующих полей в таблице релизов(особенно последних двух):

```
search_status
moon_player
last
rating
code
block
```

И в таблице `users` - `user_values`

**Comment by poiuty** [comment]
@Asethon, добрый день.

`search_status` - поиск в таблице по статусу
https://github.com/anilibria/anilibria/blob/master/pages/new.php#L115-L126
https://github.com/anilibria/anilibria/blob/master/js/tables.js#L29-L36
https://github.com/anilibria/anilibria/blob/master/private/func.php#L2009

`moonplayer` - ссылка на внешний плеер (выводим через iframe).
https://github.com/anilibria/anilibria/blob/master/private/func.php#L1244
https://github.com/anilibria/anilibria/blob/master/private/template/release.html#L69

`rating` - рейтинг релиза, сколько раз добавили в избранное.
https://github.com/anilibria/anilibria/blob/master/private/cron/rating.php
https://github.com/anilibria/anilibria/blob/master/private/func.php#L2471-L2477

`code` - url адрес страницы.
https://github.com/anilibria/anilibria/blob/master/private/func.php#L1207-L1208

`block` - блокировка по geo, например RU, EE, DE.
https://github.com/anilibria/anilibria/blob/master/private/func.php#L1215-L1218
https://github.com/anilibria/anilibria/blob/master/private/func.php#L1137-L1143

`user_values` - данные пользователя, выводим на странице cp.php
